-- Portfolio ("/") contact form. Run in the Supabase SQL Editor of the project
-- referenced by VITE_PORTFOLIO_SUPABASE_URL. Safe to re-run.

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  service text,
  message text not null,
  file_urls jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;

drop policy if exists "public can submit inquiries" on public.inquiries;
create policy "public can submit inquiries"
on public.inquiries for insert to anon
with check (
  length(trim(name)) between 2 and 100
  and length(trim(email)) between 5 and 200
  and length(trim(message)) between 10 and 5000
);
-- No public SELECT policy: read inquiries from the Supabase dashboard.

-- Storage bucket for requirement files (public so the saved links open for you)
insert into storage.buckets (id, name, public)
values ('requirements', 'requirements', true)
on conflict (id) do nothing;

drop policy if exists "public can upload requirement files" on storage.objects;
create policy "public can upload requirement files"
on storage.objects for insert to anon
with check (bucket_id = 'requirements');
