-- Run this in Supabase SQL Editor.
create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  business text,
  service text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_submissions enable row level security;

-- Public visitors may submit enquiries.
create policy "public can submit contact enquiries"
on public.contact_submissions
for insert
to anon
with check (
  length(trim(name)) between 2 and 100
  and length(trim(email)) between 5 and 200
  and length(trim(message)) between 5 and 5000
);

-- No public SELECT policy: visitors cannot read other enquiries.
-- Read/manage enquiries from the Supabase dashboard or an authenticated admin system.
